name: se5_lab2_refactoring
description: Simple PWD Registry project for Software Engineering Lab 2 Refactoring.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
